
List<String> pueblosColombia = [
  'Villa de Leyva, Boyacá',
  'Salento, Quindío',
  'Barichara, Santander',
  'Guatapé, Antioquia',
  'Jardín, Antioquia',
  'Raquira, Boyacá',
  'Girón, Santander',
  'Honda, Tolima',
  'Mompox, Bolívar',
  'Zipaquirá, Cundinamarca',
  'Tunja, Boyacá',
  'Villavicencio, Meta',
  'Manizales, Caldas',
  'San Agustín, Huila',
  'San Gil, Santander',
  'Leticia, Amazonas',
  'Armenia, Quindío',
  'Bucaramanga, Santander',
];